### ISSUE TITLE
Make EDEN Contact Form Functional

### ISSUE THREAD

**Issue by bunthius** [tksventures/eden-landingpage#2]
## Problem
Contact form at the bottom of the page is currently non-functional and needs to send a message to our designated email.

## Solution

- [ ] @tks-wagner @Gallred please provide the email address that EDEN contact inquiries will be received
- [ ] hookup the contact form with our standard email service used in other apps, here is the reference contact form: hhttps://tksventures.github.io/eden-landingpage/

**Comment by Gallred** [comment]
Let's use support@multichain.ventures for the web form across all three sites... for now.  Once we have domains configured for EDEN and Cubed, we'll configure a basic support email for each.
